### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by choilive** [tmallz/Tim-OMalley-Homework-10#1]

**Comment by tmallz** [comment]
why lol

**Comment by choilive** [comment]
Yeah I'd like to report a bug. There's no code in this repo :)

**Comment by tmallz** [comment]
ah shit, thanks for letting me know

**Comment by choilive** [comment]
Np fam

**Comment by tmallz** [comment]
using tailwinds CSS for this one

**Comment by tmallz** [comment]
the code has been added
